### ISSUE TITLE
What direction are you going

### ISSUE THREAD

**Issue by odama626** [romgrk/web-toolkit#9]
This is really cool and I think this would be awesome for creating deno executables or electron apps but I hate adwaita, do you plan to make this compatible with themes in the future?

Also, I'm decent with react / bundling and would like to help out  what would you like me to help you with?

**Comment by romgrk** [comment]
Hey,

So yes the reason I've created the project is that at work I often need to create web applications, not so much web sites, but really applications for which web design patterns aren't as optimal as desktop UI patterns would be. I initially wasn't thinking about using adwaita but when I realized I could port it I picked it fairly easily because unlike you, I happen to enjoy the adwaita theme a lot :smile: 

Even though I haven't made much progress towards that for now, I am planning on supporting light & dark adwaita themes. But I still don't have a plan for how to make it work, for now the project uses a single stylesheet for all styling, no CSS-in-JS, due to using a port of the original adwaita CSS stylesheet. All this to say that in theory, it would be possible to support other themes.

In practice however, as I personally don't have interest in using anything else than adwaita, the chances of it happening are low for now and will depend on having other contributors. The only way I would invest my time in a theme other than adwaita would be if it was something better designed than adwaita, but I have yet to see it. For the record, here is what I think of themes:
 - Windows: never
 - Material: ugly
 - Bootstrap: v3 good, v4 less good
 - Semantic UI: quite good
 - macOS: very good
 - adwaita: great

If you're interested in having themes integrated we could open a new issue to make a roadmap towards that.

As for the rest I'd be super happy to have help, here are the things to do in approximate order of priority:
 - Create webpack (or something else) scripts to prepare this package for distribution. Currently we're not exporting anything. Concerns:
   - Things must be properly exported and tree-shakeable (components, styles, & SVG icons)
   - It would be nice to be able to spawn a development setup quickly that has quick-reload and everything needed for development. Currently it's `react-scripts start` but we'll probably need to eject to setup bundling & exports correctly
   - It would also be nice to setup a sub-package for the documentation/showcase website, this is important to increase adoption
   - This discussion can be continued in https://github.com/romgrk/web-toolkit/issues/8
 - Finish implementing missing components (mainly Table I think)
 - Fix bugs & performance issues (tracking issue: #10)
 - Themes
 - Ensure components are documented and propTyped properly
 - Ensure components are accessible (ARIA attributes)

If you're interested in working on bundling it would be great, having a usable first-version will help to attract users & therefore contributors.

**Comment by odama626** [comment]
> Ensure components are documented and propTyped properly

I think it could be a good idea to look into using typescript as well since it seems most of the react community is heading that way

> Themes

I tend to agree with you as far as the examples you posted,  I was thinking maybe it would be possible to write a conversion script or something similar in the future to convert gtk themes to a stylesheet that could work for web-toolkit so the applications can seamlessly fit into the users system.  the most recent theme I've been enjoying in gnome for instance is [dracula](https://draculatheme.com/gtk)

**Comment by romgrk** [comment]
Sorry for the delay in all issues, I wasn't available for coding this last month.

Re Typescript: Yes, I've been a bit hesitant because it takes a bit longer to code, but I'd be ok with switching to it at some point and converting files as they are modified.

Re Themes: Your plan is quite ambitious, the changes I did where quite substantial, and that GTK stylesheet is all over the place. Deeply nested selectors, mismatching elements, mismatching structure. My feeling is that if it was done it would end up being too brittle. But if it's doable it would be awesome.

**Comment by romgrk** [comment]
Closing but re-open an issue or a discussion for any other questions/comments.
